apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{service}}
  namespace: {{namespace}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: {{service}}
        version: v1
    spec:
      containers:
      - name: {{service}}
        image: {{image}}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9081
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: {{profiles}}
      imagePullSecrets:
        - name: ecr-secret
---
kind: Service
apiVersion: v1
metadata:
  namespace: {{namespace}}
  name: {{service}}
spec:
  selector:
    k8s-app: {{service}}
  ports:
  - port: 9081
    name: http
    protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{service}}
  namespace: {{namespace}}
spec:
  rules:
  - host: {{service}}.{{team}}.cloud.school.thoughtworks.cn
    http:
      paths:
      - path: /
        backend:
          serviceName: {{service}}
          servicePort: 9081
